### ISSUE TITLE
add continous integration

### ISSUE THREAD

**Issue by defreek** [Lumi-education/Lumi#35]
Once we have linting setup, it's important that we setup continous integration so that these rules are enforced before merging code. This way we can also run tests when a PR is submitted (once we have them). I suggest we use Travis CI (https://travis-ci.org/) as it's free for open source projects.

@JPSchellenberg i have requested access to integrate the CI.

**Comment by JPSchellenberg** [comment]
I granted the access to integrate Travis. I think CI is very important and should be integrated as soon as possible.

**Comment by JPSchellenberg** [comment]
Can you set up Travis? Our what do you need to set up Tavis? :smile:

**Comment by JPSchellenberg** [comment]
Ok, I think Travis is set up. We just need the .travis.yml

**Comment by defreek** [comment]
Ok, i'll set up yarn first and then add the config.
