### ISSUE TITLE
remove font-stylesheet in index.html that depends on an internet-connection

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumi-education/Lumi#42]
The `<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">` in the index.html can not be loaded, when Lumi is used without internet and the `resolve host` causes the client to load very long.

**Comment by defreek** [comment]
We should also have the index.html file generated by webpack so the client bundles can contain a hash so they will be correctly cached by the browser.
