### ISSUE TITLE
use socket.io instead of websockets

### ISSUE THREAD

**Issue by JPSchellenberg** [Lumi-education/Lumi#44]
The real-time functionality is currently achieved by a simple websocket-server that runs on port 8081. (server/core/websocket.ts). https://github.com/Lumi-education/Lumi/pull/30/commits/9f50f7374d5e649f23e32f5b2b359e44bd91f86b
We should switch from the simple websocket-server to a socket.io-server that binds on port 80 through the express-server, so we don't have to use multiple ports and have a fallback.
But the express-server is clustered in production-environment and we need a way to communicate between the different processes. 

https://socket.io/docs/using-multiple-nodes/
https://github.com/indutny/sticky-session

**Comment by defreek** [comment]
I've implemented socket.io in another project of mine so i can take this one. On another note, why do we actually need this clustering? It seems to overcomplicate things and seeing that the app will only be used in a classroom, i don't think the load of the server will ever be high.

**Comment by JPSchellenberg** [comment]
Hmm.. good point. I thought it would be better to use all 4 cores of the raspberry pi to improve performance, but I haven't tested it. If one core is sufficient we could just spawn one process. I wanted to integrate some kind of loading-test in the future (https://artillery.io). Maybe I will try to test how the clustering improves the performance this weekend.

**Comment by defreek** [comment]
I might be wrong but adding these clusters may be useful when you have to serve 1000s or 10000s of simultaneous requests, which in a classroom will not be the case at all. You could try the load testing, but do you think it will actually reach a load like that in real life? Just my two cents.

**Comment by JPSchellenberg** [comment]
You might be right. Then let's start with the simple approach and a single process. If we have to improve performance we can add the cluster later on.
